"""统一导出 SFT 数据、编码、训练与评测能力。"""

from .dataset import (
    DatasetBuildError,
    SftDatasetResult,
    build_sft_dataset,
    dataset_split_path,
    validate_sft_dataset,
)
from .encoding import (
    SftConfig,
    SftTrainingError,
    TokenizedSample,
    encode_messages,
    load_sft_config,
    load_tokenized_samples,
)
from .evaluation import (
    GeneratedReply,
    GenerationScore,
    MaskedTokenStats,
    chunked_masked_stats,
    decode_generation,
    evaluate_rows,
    evaluate_sft,
    evaluate_sft_loss,
    evaluate_tokenized_samples,
    score_generation,
)
from .knowledge_evaluation import (
    KnowledgeProbe,
    load_knowledge_probes,
    run_knowledge_evaluation,
    score_compositional_answer,
    score_recall_answer,
)
from .merge import merge_sft_adapter
from .mix import SftMixConfig, apply_sft_mix, load_sft_mix
from .trainer import (
    LORA_TARGET_MODULES,
    ChunkedCrossEntropy,
    OptimizationCheckpoint,
    OptimizationResult,
    adapter_source_files,
    attach_lora,
    optimize,
    publish_adapter,
    resolve_device,
    save_last_checkpoint,
    train_sft,
)

__all__ = [
    "LORA_TARGET_MODULES",
    "ChunkedCrossEntropy",
    "DatasetBuildError",
    "GeneratedReply",
    "GenerationScore",
    "KnowledgeProbe",
    "MaskedTokenStats",
    "OptimizationCheckpoint",
    "OptimizationResult",
    "SftConfig",
    "SftDatasetResult",
    "SftMixConfig",
    "SftTrainingError",
    "TokenizedSample",
    "adapter_source_files",
    "apply_sft_mix",
    "attach_lora",
    "build_sft_dataset",
    "chunked_masked_stats",
    "dataset_split_path",
    "decode_generation",
    "encode_messages",
    "evaluate_rows",
    "evaluate_sft",
    "evaluate_sft_loss",
    "evaluate_tokenized_samples",
    "load_knowledge_probes",
    "load_sft_config",
    "load_sft_mix",
    "load_tokenized_samples",
    "merge_sft_adapter",
    "optimize",
    "publish_adapter",
    "resolve_device",
    "run_knowledge_evaluation",
    "save_last_checkpoint",
    "score_compositional_answer",
    "score_generation",
    "score_recall_answer",
    "train_sft",
    "validate_sft_dataset",
]
